import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.co",
      href: "/favicon.co",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={jost.className}>
        <link rel="icon" href="./favicon.ico" />
        {children}
      </body>
    </html>
  );
}
